Субъект РФ: 'subject'
МО: 'mo'
ИНН: 'inn'
Статус: 'status'
Тип вывода из оборота: 'type'
ГТИН: 'gtin'
Серия: 'series'
"Дозы\n(количество доз в упаковке (флаконе))": 'doses_per_packages'
"Количество\nУпаковок": 'packages_amount'
"Количество\nДоз": 'doses_amount'
Срок годности: 'date_of_expiration'
Просрочено дней: 'days_overdue'