version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./solution.sql:/var/lib/postgresql/solution.sql
      - ./result/:/var/lib/postgresql/test
      - ./data_dump/dump_utf8.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  db:
    driver: local